# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - csc307

on:
    push:
        branches:
            - signin-hash
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: npm install, build, and test
              run: |
                  cd packages/backend
                  npm install -g nodemon
                  npm install cors
                  npm install dotenv
                  npm install express
                  npm install mongoose
                  npm run -w backend build --if-present
                  npm run -w backend test --if-present

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r
              working-directory: packages/backend

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: packages/backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0917878BE04C437FB6B355B5444C5E37 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53C290A32B8549CFACD0933595330049 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EB081DEABB2B489B85FE0BD4A433153F }}

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'csc307'
                  slot-name: 'Production'
                  package: .
