# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - backend-task-arena

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: npm install, build, and test
              
              run: |
                  npm install -g nodemon --workspace=false
                  npm install --workspaces=false
                  pwd
                  ls
                  npm run -w backend build --if-present
                  npm run -w backend test --if-present
              working-directory: packages/backend

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r
              working-directory: packages/backend

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: packages/backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8B54CD34EEC84601B47BB7BE5CF1CDCD }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A409FE67CDEF4B8D95A056037414C204 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F8942364C6E44E348B26364B6ED501BD }}

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'backend-task-arena'
                  slot-name: 'Production'
                  package: .
